apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver-docker
  name: webserver-docker
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver-docker
  type: LoadBalancer
