apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver-docker
  name: webserver
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver-docker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webserver-docker
    spec:
      containers:
      - image: harbor.site-a.vcf.lab/library/webserver-docker:demo4
        imagePullPolicy: Always
        name: webserver-docker
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
