apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  name: demo-vm2
  namespace: argocd
  labels:
    vm-selector: demo-vm2
    demo-vm2-lb: vm2-lb-selector
    topology.kubernetes.io/zone: z-wld-a
spec:
  className: best-effort-small
  # Friendly image name: Ubuntu 22.04
  imageName: vmi-4376698549fa77811
  storageClass: vks-storage-policy
  powerState: PoweredOn
  network:
    hostName: demo-vm2
    domainName: site-a.vcf.lab
  bootstrap:
    cloudInit:
      cloudConfig:
        defaultUserEnabled: true
        ssh_pwauth: true
        users:
          - name: demo
            passwd:
              name: demo-vm2-bootstrap-secret
              key: demo-passwd
            lock_passwd: false
            sudo: ALL=(ALL) NOPASSWD:ALL
