apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-test
  namespace: argocd
  labels:
    vm-selector: vm-test
    vm-lb-s3i4: vm-lb-selector
    topology.kubernetes.io/zone: z-wld-a
spec:
  className: best-effort-small
  # Friendly image name: noble-server-cloudimg-amd64
  imageName: vmi-ecee470dea395555a
  storageClass: vks-storage-policy
  powerState: PoweredOn
  volumes:
    - name: vm-kj3q-pvc-0
      persistentVolumeClaim:
        claimName: vm-kj3q-pvc-0
  network:
    interfaces:
      - name: eth89
        network:
          name: public-subnet
          kind: SubnetSet
    hostName: vm-test
    domainName: site-a.vcf.lab
  bootstrap:
    cloudInit:
      cloudConfig:
        defaultUserEnabled: true
        ssh_pwauth: true
        users:
          - name: vcf
            passwd:
              name: vm-test-bootstrap-secret
              key: vcf-passwd
            lock_passwd: false
            sudo: ALL=(ALL) NOPASSWD:ALL
